---
- hosts: webservers
  tasks:
 
  - name: installations
    apt_repository: repo='ppa:openjdk-r/ppa'
    
  - name: open jdk
    apt: pkg=openjdk-8-jdk

  - name: tomcat
    apt: pkg=tomcat7
      
  - name: JAVA HOME
    lineinfile:
     dest=/etc/default/tomcat7 line="JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" state=present insertafter=EOF create=True

  - name: .war file transfer
    copy:
      src: "/var/lib/jenkins/workspace/petclinic/target/petclinic.war"
      dest: "/var/lib/tomcat7/webapps/"
    notify:
     - Restart tomcat
